apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mavenwebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
	  app: mavenwebapp
  strategy:
    type: rollingUpdate
	rollingUpdate:
	  maxUnavailable: 1
	  maxSurge: 1
	minReadySeconds: 30
  template:
    matadata: 
	  name: mavenwebapppod
	  labels:
	    app: mavenwebapp
	spec:
	  containers:
	  - name: mavenwebappcontainer
	    image: ayyappa376/mavenweb
        ports:
        - containerPort: 80	
		
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappservice
 labels:
   app: mavenwebapp
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort:8080
